require(tuneR)
comppath <- "testdata"
source("soncompare.R")

source("test-sonopts.R")
source("test-mapping.R")
source("test-scaleshortcuts.R")
source("test-render.R")
source("test-setting.R")
source("test-shape-scatter.R")
source("test-sonify.R")
source("test-shape-dotplot.R")
source("test-facet.R")
source("test-shape-histogram.R")
source("test-play.R")
